name: Ubuntu CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: gcc
            os: ubuntu-latest
          - compiler: clang
            os: ubuntu-latest
          - compiler: clang
            os: macos-latest
          - compiler: gcc
            os: macos-latest
          - compiler: msvc
            os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install GNU C/C++ Compiler
        if: ${{ matrix.compiler == 'gcc' }}
        run: |
          export GNU_CC=gcc
          export GNU_CXX=g++

      - name: Install LLVM Clang
        if: ${{ matrix.compiler == 'clang' }}
        run: |
          export LLVM_CC=clang
          export LLVM_CXX=clang++

      - name: Install OpenCV (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libopencv-dev

      - name: Install OpenCV (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install opencv

      - name: CMake Build
        run: |
          cmake . -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=Release
          cmake --build ${{runner.workspace}}/build --config Release --parallel 2
